server:
  port: 8304

spring:
  application:
    name: error-monitor
  cloud:
    function:
      definition: jwtErrorConsumer;signatureErrorConsumer
    stream:
      bindings:
        jwtErrorConsumer-in-0:
          destination: scst-security-jwt-error
          contentType: application/json
          group: error-monitor
        signatureErrorConsumer-in-0:
          destination: scst-security-signature-error
          contentType: application/json
          group: error-monitor

management:
  metrics:
    enable:
      all: true
  influx:
    metrics:
      export:
        enabled: true
        step: 10s
        bucket: scst
        token: A4XPNzOdvdbJQudj0th08N-aNH65vdfzLlFS4YlNy9leoUPLzuKUmD7hoNKdieejs9CHd0eFWsM_9IDAmI9GWQ==
        org: vmware
